"""adding pokemon table

Revision ID: 3b4bae50a723
Revises: 093c88bbe822
Create Date: 2023-08-25 19:24:02.483845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4bae50a723'
down_revision = '093c88bbe822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.drop_table('posts')
    op.drop_table('users')
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('poke_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poke_def', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poke_att', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poke_sprite', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('level')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('date_created')
        batch_op.drop_column('poke_sprite')
        batch_op.drop_column('poke_att')
        batch_op.drop_column('poke_def')
        batch_op.drop_column('poke_hp')
        batch_op.drop_column('poke_name')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('caption', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
